misra: remove flexible array
UAVCAN/libcanard pull request #192
Opened 2022-03-13 05:45 UTC by coderkalyan

Closes #183

2022-03-13 05:46 UTC, coderkalyan commented
As per MISRA, flexible array members should be replaced with maximum-size allocation and the following pointer arithmetic to avoid undefined behavior.

2022-03-14 10:20 UTC, pavel-kirienko requested changes

2022-03-14 10:20 UTC, pavel-kirienko commented on libcanard/canard.c
> +    uint8_t payload_buffer[CANARD_MTU_CAN_FD];  // NOSONAR
1. The comment above is no longer relevant and should be either edited or removed.
2. Can we please introduce a new definition in the header file like this in order to remove the implicit dependency on the set of supported transports here:

```c
#define CANARD_MTU_MAX CANARD_MTU_CAN_FD
```

2022-03-14 10:20 UTC, pavel-kirienko commented on libcanard/canard.c
> +    TxItem* const out = (TxItem*) ins->memory_allocate(ins, sizeof(TxItem) - CANARD_MTU_CAN_FD + payload_size);
```suggestion
    TxItem* const out = (TxItem*) ins->memory_allocate(ins, sizeof(TxItem) - CANARD_MTU_MAX + payload_size);
```

Assuming that the above suggestion is accepted.

2022-03-21 10:23 UTC, pavel-kirienko requested changes

2022-03-21 10:23 UTC, pavel-kirienko commented on libcanard/canard.c
> +#define CANARD_MTU_MAX CANARD_MTU_CAN_FD
I think this actually should be in the header file (as I wrote earlier) because this is also useful for the API.

2022-03-21 10:23 UTC, pavel-kirienko commented on libcanard/canard.c
> +    uint8_t           payload_buffer[CANARD_MTU_MAX];  // NOSONAR
```suggestion
    uint8_t           payload_buffer[CANARD_MTU_MAX];
```

2022-03-28 07:59 UTC, pavel-kirienko approved these changes

2022-03-28 08:29 UTC, merged